import React from 'react';

const categoryMap = {
  'Airtel Free Net': 'এয়ারটেল ফ্রি নেট',
  'Android Custom ROM': 'অ্যান্ড্রয়েড কাস্টম রম',
  'Android Phone Review': 'অ্যান্ড্রয়েড ফোন রিভিউ',
  'Android Root': 'অ্যান্ড্রয়েড রুট',
  'Android Tips': 'অ্যান্ড্রয়েড টিপস',
  'Android Xposed Framework': 'অ্যান্ড্রয়েড এক্সপোজড ফ্রেমওয়ার্ক',
  'Apps Review': 'অ্যাপস রিভিউ',
  'Banglalink Free Net': 'বাংলালিংক ফ্রি নেট',
  'Binning': 'বিনিং',
  'Blogger': 'ব্লগার',
  'Broadband Tricks': 'ব্রডব্যান্ড ট্রিকস',
  'C Programming': 'সি প্রোগ্রামিং',
  'Corona Virus Update Bangladesh': 'করোনা ভাইরাস আপডেট বাংলাদেশ',
  'Cryptocurrency': 'ক্রিপ্টোকারেন্সি',
  'Cyber Security News': 'সাইবার সিকিউরিটি নিউজ',
  'Cyber Security Tutorial': 'সাইবার সিকিউরিটি টিউটোরিয়াল',
  'Education': 'শিক্ষা',
  'Education Guideline': 'শিক্ষা নির্দেশিকা / গাইডলাইন',
  'Electronics': 'ইলেকট্রনিক্স',
  'Facebook Tricks': 'ফেসবুক ট্রিকস',
  'Featured': 'ফিচারড',
  'Freelancing': 'ফ্রিল্যান্সিং',
  'Games Review': 'গেমস রিভিউ',
  'GP Free Net': 'জিপি ফ্রি নেট',
  'Guidelines': 'গাইডলাইনস',
  'Hadith & Quran': 'হাদিস ও কুরআন',
  'Hot': 'হট',
  'HSC Exam Result': 'এইচএসসি পরীক্ষা ফলাফল',
  'Islamic Story': 'ইসলামিক গল্প',
  'Java Mobile': 'জাভা মোবাইল',
  'Java Programming': 'জাভা প্রোগ্রামিং',
  'JavaScript': 'জাভাস্ক্রিপ্ট',
  'JSC Exam Result': 'জেএসসি পরীক্ষা ফলাফল',
  'Lifestyle': 'লাইফস্টাইল',
  'Linux': 'লিনাক্স',
  'Mobile Banking': 'মোবাইল ব্যাংকিং',
  'Mobile Review': 'মোবাইল রিভিউ',
  'Movie Review': 'মুভি রিভিউ',
  'Offer': 'অফার',
  'Online Income': 'অনলাইন আয়',
  'Operating System': 'অপারেটিং সিস্টেম',
  'Operator News': 'অপারেটর নিউজ',
  'PDF Book': 'পিডিএফ বই',
  'PHP': 'পিএইচপি',
  'Promo Code': 'প্রোমো কোড',
  'Python Programming': 'পাইথন প্রোগ্রামিং',
  'Robi Free Net': 'রবি ফ্রি নেট',
  'SEO Tricks': 'এসইও ট্রিকস',
  'Sponsored Post': 'স্পন্সরড পোস্ট',
  'SSC Exam Result': 'এসএসসি পরীক্ষা ফলাফল',
  'Symbian Mobile': 'সিম্বিয়ান মোবাইল',
  'Symphony Custom ROM': 'সিনফনি কাস্টম রম',
  'Tech News': 'টেক নিউজ',
  'Technology Update': 'প্রযুক্তি আপডেট',
  'Theme Review': 'থিম রিভিউ',
  'Tools': 'টুলস',
  'Trainer Competition': 'ট্রেইনার প্রতিযোগিতা',
  'TrickBD Notice': 'ট্রিকবিডি নোটিশ',
  'Tricks': 'ট্রিকস',
  'Uncategorized': 'আনক্যাটেগরাইজড / শ্রেণিবিহীন',
  'Walton Custom ROM': 'ওয়ালটন কাস্টম রম',
  'Wapk': 'ওয়াপক',
  'Web Development': 'ওয়েব ডেভেলপমেন্ট',
  'Website': 'ওয়েবসাইট',
  'Windows Mobile': 'উইন্ডোজ মোবাইল',
  'Windows PC': 'উইন্ডোজ পিসি',
  'WordPress': 'ওয়ার্ডপ্রেস',
  'YouTube': 'ইউটিউব',
};

const CategoryTranslator = ({ category }) => {
  const translatedCategory = categoryMap[category] || category;
  return <span>{translatedCategory}</span>;
};

export default CategoryTranslator;